
# define prune ratios for your network

prune_ratios:
   conv1.weight:
     0
   layers.0.conv1.weight:
     0.7
   layers.0.conv2.weight:
     0.7
   layers.0.conv3.weight:
     0.7
   layers.0.shortcut.0.weight:
     0.7
   layers.1.conv1.weight:
     0.7
   layers.1.conv2.weight:
     0.7
   layers.1.conv3.weight:
     0.7
   layers.1.shortcut.0.weight:
     0.7
   layers.2.conv1.weight:
     0.7
   layers.2.conv2.weight:
     0.7
   layers.2.conv3.weight:
     0.7
   layers.3.conv1.weight:
     0.7
   layers.3.conv2.weight:
     0.7
   layers.3.conv3.weight:
     0.7
   layers.4.conv1.weight:
     0.7
   layers.4.conv2.weight:
     0.7
   layers.4.conv3.weight:
     0.7
   layers.5.conv1.weight:
     0.7
   layers.5.conv2.weight:
     0.7
   layers.5.conv3.weight:
     0.7
   layers.6.conv1.weight:
     0.7
   layers.6.conv2.weight:
     0.7
   layers.6.conv3.weight:
     0.7
   layers.7.conv1.weight:
     0.7
   layers.7.conv2.weight:
     0.7
   layers.7.conv3.weight:
     0.7
   layers.8.conv1.weight:
     0.7
   layers.8.conv2.weight:
     0.7
   layers.8.conv3.weight:
     0.7
   layers.9.conv1.weight:
     0.7
   layers.9.conv2.weight:
     0.7
   layers.9.conv3.weight:
     0.7
   layers.10.conv1.weight:
     0.7
   layers.10.conv2.weight:
     0.7
   layers.10.conv3.weight:
     0.7
   layers.10.shortcut.0.weight:
     0.7
   layers.11.conv1.weight:
     0.7
   layers.11.conv2.weight:
     0.7
   layers.11.conv3.weight:
     0.7
   layers.12.conv1.weight:
     0.7
   layers.12.conv2.weight:
     0.7
   layers.12.conv3.weight:
     0.7
   layers.13.conv1.weight:
     0.7
   layers.13.conv2.weight:
     0.7
   layers.13.conv3.weight:
     0.7
   layers.14.conv1.weight:
     0.7
   layers.14.conv2.weight:
     0.7
   layers.14.conv3.weight:
     0.7
   layers.15.conv1.weight:
     0.7
   layers.15.conv2.weight:
     0.7
   layers.15.conv3.weight:
     0.7
   layers.16.conv1.weight:
     0.7
   layers.16.conv2.weight:
     0.7
   layers.16.conv3.weight:
     0.7
   layers.16.shortcut.0.weight:
     0.7
   conv2.weight:
     0.7




